"""
Type stub for QTermWidget — Python bindings for the QTermWidget C++ library.
Generated from qtermwidget.sip (QTermWidget 2.2.0, pyqtbuild).
"""

from enum import IntEnum
from typing import Optional

from PyQt6.QtCore import pyqtSignal, QSize, QUrl
from PyQt6.QtGui import QFont, QKeyEvent, QResizeEvent
from PyQt6.QtWidgets import QWidget


class QTermWidget(QWidget):

    class ScrollBarPosition(IntEnum):
        NoScrollBar = 0
        ScrollBarLeft = 1
        ScrollBarRight = 2

    class KeyboardCursorShape(IntEnum):
        BlockCursor = 0
        UnderlineCursor = 1
        IBeamCursor = 2

    # Signals
    finished: pyqtSignal
    copyAvailable: pyqtSignal  # bool
    termGetFocus: pyqtSignal
    termLostFocus: pyqtSignal
    termKeyPressed: pyqtSignal  # QKeyEvent*
    urlActivated: pyqtSignal    # QUrl, bool
    bell: pyqtSignal            # str
    activity: pyqtSignal
    silence: pyqtSignal
    sendData: pyqtSignal        # bytes, int
    titleChanged: pyqtSignal
    receivedData: pyqtSignal    # str
    profileChanged: pyqtSignal  # str

    def __init__(self, startnow: int = 1, parent: Optional[QWidget] = None) -> None: ...

    # Setup
    def startShellProgram(self) -> None: ...
    def startTerminalTeletype(self) -> None: ...
    def setShellProgram(self, progname: str) -> None: ...
    def setArgs(self, args: list[str]) -> None: ...
    def setEnvironment(self, environment: list[str]) -> None: ...
    def setWorkingDirectory(self, dir: str) -> None: ...
    def workingDirectory(self) -> str: ...
    def changeDir(self, dir: str) -> None: ...

    # Font & appearance
    def setTerminalFont(self, font: QFont) -> None: ...
    def getTerminalFont(self) -> QFont: ...
    def setTerminalOpacity(self, level: float) -> None: ...
    def setColorScheme(self, name: str) -> None: ...
    def getAvailableColorSchemes(self) -> list[str]: ...
    @staticmethod
    def availableColorSchemes() -> list[str]: ...
    @staticmethod
    def addCustomColorSchemeDir(custom_dir: str) -> None: ...
    def setKeyboardCursorShape(self, shape: "QTermWidget.KeyboardCursorShape") -> None: ...

    # Scroll & history
    def setScrollBarPosition(self, pos: "QTermWidget.ScrollBarPosition") -> None: ...
    def scrollToEnd(self) -> None: ...
    def setHistorySize(self, lines: int) -> None: ...
    def historyLinesCount(self) -> int: ...

    # Input / output
    def sendText(self, text: str) -> None: ...
    def clear(self) -> None: ...
    def setFlowControlEnabled(self, enabled: bool) -> None: ...
    def flowControlEnabled(self) -> bool: ...
    def setFlowControlWarningEnabled(self, enabled: bool) -> None: ...

    # Selection
    def selectedText(self, preserveLineBreaks: bool = True) -> str: ...
    def setSelectionStart(self, row: int, column: int) -> None: ...
    def setSelectionEnd(self, row: int, column: int) -> None: ...
    def getSelectionStart(self, row: int, column: int) -> None: ...
    def getSelectionEnd(self, row: int, column: int) -> None: ...

    # Key bindings
    def keyBindings(self) -> str: ...
    def setKeyBindings(self, kb: str) -> None: ...
    @staticmethod
    def availableKeyBindings() -> list[str]: ...

    # Monitoring
    def setMonitorActivity(self, on: bool) -> None: ...
    def setMonitorSilence(self, on: bool) -> None: ...
    def setSilenceTimeout(self, seconds: int) -> None: ...

    # Process info
    def getShellPID(self) -> int: ...
    def getForegroundProcessId(self) -> int: ...
    def getPtySlaveFd(self) -> int: ...

    # Misc
    def sizeHint(self) -> QSize: ...
    def setTerminalSizeHint(self, on: bool) -> None: ...
    def terminalSizeHint(self) -> bool: ...
    def setMotionAfterPasting(self, mode: int) -> None: ...
    def screenColumnsCount(self) -> int: ...
    def setAutoClose(self, on: bool) -> None: ...
    def title(self) -> str: ...
    def icon(self) -> str: ...
    def toggleShowSearchBar(self) -> None: ...
    def setSize(self, size: QSize) -> None: ...

    # Slots
    def copyClipboard(self) -> None: ...
    def pasteClipboard(self) -> None: ...
    def pasteSelection(self) -> None: ...
    def zoomIn(self) -> None: ...
    def zoomOut(self) -> None: ...
