source "https://rubygems.org"

ruby "3.3.0"

gem "rails", "~> 7.1"
gem "pg", "~> 1.5"
gem "puma", "~> 6.0"
gem "redis", "~> 5.0"
gem "sidekiq", "~> 7.0"
gem "devise", "~> 4.9"
gem "pundit", "~> 2.3"
gem "image_processing", "~> 1.12"

group :development, :test do
  gem "rspec-rails", "~> 6.0"
  gem "factory_bot_rails"
  gem "faker"
  gem "byebug"
end

group :development do
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
  gem "annotate"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "simplecov", require: false
end
