def build_painter_styles(bg, fg, bd, gl) -> dict:
    qss_QPainter = {
        "painter_area": bg.get("painter_area", "#2B2D30"),
        "painter_text": fg.get("painter_text", "#888888"),
        "painter_text_active": fg.get("painter_text_active", "#FFFFFF"),
        "painter_active_bg": bg.get("painter_active_bg", "#3C3F41"),
        "painter_lines": bd.get("painter_lines", "#2B2D30"),
        "keyword": fg.get("keyword", "deepskyblue"),
        "builtin": fg.get("builtin", "#FFD700"),
        "comment": fg.get("comment", "#888888"),
        "string": fg.get("string", "#98C379"),
        "number": fg.get("number", "#FF6C6B"),
        "function": fg.get("function", "#61AFEF"),
        "preprocessor": fg.get("preprocessor", "#C586C0"),
        "char": fg.get("char", "#D69D85"),
        "type": fg.get("type", "#4EC9B0"),
        "class": fg.get("class", "#E5C365"),
        "namespace": fg.get("namespace", "#D8A0F5"),
        "template": fg.get("template", "#D8A0F5"),
        "regex": fg.get("regex", "#D69D85"),
        "xmlcomment": fg.get("xmlcomment", "#888888"),
        "attribute": fg.get("attribute", "#D69D85"),
        "interpolation": fg.get("interpolation", "#D8A0F5"),
        "method": fg.get("method", "#D69D85"),
        "package": fg.get("package", "#D8A0F5"),
        "rune": fg.get("rune", "#E5C365"),
        "variable": fg.get("variable", "#D69D85"),
        "label": fg.get("label", "#D69D85"),
        "directive": fg.get("directive", "#FFD700"),
        "instruction": fg.get("instruction", "deepskyblue"),
        "register": fg.get("register", "#4EC9B0"),
        "symbol": fg.get("symbol", "#61AFEF"),
        "section": fg.get("section", "#FFD700"),
        "identifier": fg.get("identifier", "#FFD700"),
        "shebang": fg.get("shebang", "#4EC9B0"),
        "command": fg.get("command", "#D69D85"),
        "heredoc": fg.get("heredoc", "#C586C0"),
        "block_comment": fg.get("block_comment", "#98A398"),
        "tag": fg.get("tag", "#FFD700"),
        "attribute_value": fg.get("attribute_value", "#98C379"),
        "doctype": fg.get("doctype", "#C586C0"),
        "entity": fg.get("entity", "deepskyblue"),
        "script": fg.get("script", "#61AFEF"),
        "style": fg.get("style", "#FF6C6B"),
    }

    return {
        "qss_QPainter": qss_QPainter,
    }
